// PDF-exact inspection templates matching the screenshots provided
// This replaces all previous templates and matches the exact structure shown in the PDF

export const PDF_INSPECTION_SYSTEMS = {
  // KITCHEN SECTION - Page 22
  kitchen: {
    title: "KITCHEN",
    sections: [
      {
        title: "COUNTERTOPS",
        items: [
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Recommend repair/caulking", type: "checkbox" }
        ]
      },
      {
        title: "CABINETS", 
        items: [
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Recommend repair/adjustment", type: "checkbox" }
        ]
      },
      {
        title: "PLUMBING COMPONENTS",
        items: [
          { label: "Faucet Leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak/corroded:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Sink/Faucet:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Corroded", type: "checkbox" },
          { label: "Chipped", type: "checkbox" },
          { label: "Cracked", type: "checkbox" },
          { label: "Recommend repair", type: "checkbox" },
          { label: "Functional Drainage:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Functional Flow:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" }
        ]
      },
      {
        title: "WALLS & CEILING",
        items: [
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" },
          { label: "Moisture stains", type: "checkbox" }
        ]
      },
      {
        title: "HEATING/COOLING/POWER",
        items: [
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" }
        ]
      },
      {
        title: "FLOOR",
        items: [
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Sloping", type: "checkbox" },
          { label: "Squeaks", type: "checkbox" }
        ]
      },
      {
        title: "APPLIANCES",
        subtitle: "Appliances are tested for functional operation only. A complete inspection was not performed. (See remarks page)",
        items: [
          { label: "Disposal", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Microwave", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Oven", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Exhaust fan", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Range", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Refrigerator", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Dishwasher", type: "label" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Dishwasher Air Gap or Dishwasher Drain Line Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not Visible", type: "checkbox" },
          { label: "Receptacles Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "GFCI:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Potential safety hazard(s)", type: "checkbox" }
        ]
      }
    ]
  },

  // LAUNDRY ROOM SECTION - Page 22
  laundry: {
    title: "LAUNDRY ROOM",
    sections: [
      {
        title: "LAUNDRY",
        items: [
          { label: "Laundry sink:", type: "label" },
          { label: "N/A", type: "checkbox" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Cross connections:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Heat source present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Room vented:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Dryer vented:", type: "label" },
          { label: "Wall", type: "checkbox" },
          { label: "Ceiling", type: "checkbox" },
          { label: "Floor", type: "checkbox" },
          { label: "Not vented to Exterior", type: "checkbox" },
          { label: "Recommend repair", type: "checkbox" },
          { label: "Safety hazard", type: "checkbox" },
          { label: "Plastic Dryer Vent not recommended", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Safety hazard", type: "checkbox" }
        ]
      },
      {
        title: "Electrical:",
        items: [
          { label: "Open ground/reverse polarity within 6' of water:", type: "label" },
          { label: "GFCI present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Appliances:", type: "label" },
          { label: "Washer", type: "checkbox" },
          { label: "Dryer", type: "checkbox" },
          { label: "Water heater", type: "checkbox" },
          { label: "Furnace/Boiler", type: "checkbox" },
          { label: "Water can leak on line:", type: "checkbox" },
          { label: "Wiring", type: "checkbox" },
          { label: "Not visible", type: "checkbox" }
        ]
      }
    ],
    generalComments: "The laundry tub is draining into the floor drain. This is not a recommended practice. Recommend a qualified plumber repair as necessary."
  },

  // BATHROOM(S) SECTION - Pages 23-24
  bathrooms: {
    title: "BATHROOM(S)",
    sections: [
      {
        title: "FIRST FLOOR HALF BATH",
        items: [
          { label: "Sinks:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Toilet:", type: "label" },
          { label: "Bowl Loose:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Cracked bowl", type: "checkbox" },
          { label: "Toilet leaks", type: "checkbox" },
          { label: "Caulk/Grouting Needed:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Drainage:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Water flow:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Moisture stains present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Cabinets", type: "checkbox" },
          { label: "Receptacles Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "GFCI:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Potential Safety Hazards(s)", type: "checkbox" },
          { label: "Heat source present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Window/doors:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Exhaust fan:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Noisy", type: "checkbox" }
        ]
      },
      {
        title: "MAIN FLOOR BATH",
        items: [
          { label: "Sinks:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Tubs:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not Visible", type: "checkbox" },
          { label: "Showers:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not Visible", type: "checkbox" },
          { label: "Toilet:", type: "label" },
          { label: "Bowl loose:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Cracked bowl", type: "checkbox" },
          { label: "Toilet leaks", type: "checkbox" },
          { label: "Shower/Tub area:", type: "label" },
          { label: "Ceramic/Plastic", type: "checkbox" },
          { label: "Fiberglass", type: "checkbox" },
          { label: "Masonite", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Rotted floors", type: "checkbox" },
          { label: "Caulk/Grouting Needed:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Drainage:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Water flow:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Moisture stains present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Cabinets", type: "checkbox" },
          { label: "Receptacles Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "GFCI:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Potential Safety Hazards(s)", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Heat source present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Window/doors:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Exhaust fan:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Noisy", type: "checkbox" }
        ]
      },
      {
        title: "MASTER BATH",
        items: [
          { label: "Sinks:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Showers:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not Visible", type: "checkbox" },
          { label: "Toilet:", type: "label" },
          { label: "Bowl loose:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Cracked bowl", type: "checkbox" },
          { label: "Toilet leaks", type: "checkbox" },
          { label: "Shower/Tub area:", type: "label" },
          { label: "Ceramic/Plastic", type: "checkbox" },
          { label: "Fiberglass", type: "checkbox" },
          { label: "Masonite", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Rotted floors", type: "checkbox" },
          { label: "Caulk/Grouting Needed:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Drainage:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Water flow:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Moisture stains present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Cabinets", type: "checkbox" },
          { label: "Receptacles Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "GFCI:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Potential Safety Hazards(s)", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Heat source present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Window/doors:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Exhaust fan:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Noisy", type: "checkbox" }
        ]
      },
      {
        title: "ATTIC BATH",
        items: [
          { label: "Sinks:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Tubs:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not Visible", type: "checkbox" },
          { label: "Showers:", type: "label" },
          { label: "Faucet leaks:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pipes leak:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not Visible", type: "checkbox" },
          { label: "Toilet:", type: "label" },
          { label: "Bowl loose:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Cracked bowl", type: "checkbox" },
          { label: "Toilet leaks", type: "checkbox" },
          { label: "Shower/Tub area:", type: "label" },
          { label: "Ceramic/Plastic", type: "checkbox" },
          { label: "Fiberglass", type: "checkbox" },
          { label: "Masonite", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Rotted floors", type: "checkbox" },
          { label: "Caulk/Grouting Needed:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Drainage:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Water flow:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Moisture stains present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Cabinets", type: "checkbox" },
          { label: "Receptacles Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "GFCI:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Potential Safety Hazards(s)", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Heat source present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Window/doors:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Exhaust fan:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Noisy", type: "checkbox" }
        ]
      }
    ]
  },

  // ROOMS SECTION - Pages 25-27
  rooms: {
    title: "ROOMS",
    sections: [
      {
        title: "LIVING ROOM",
        items: [
          { label: "Walls & Ceiling:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" },
          { label: "Damage", type: "checkbox" },
          { label: "Moisture stains:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Floor:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Squeaks", type: "checkbox" },
          { label: "Slopes", type: "checkbox" },
          { label: "Electrical:", type: "label" },
          { label: "Switches:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Receptacles:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Safety Hazard", type: "checkbox" },
          { label: "Cover plates missing", type: "checkbox" },
          { label: "Heating Source Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Holes:", type: "label" },
          { label: "Doors", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Egress Restricted:", type: "label" },
          { label: "N/A", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Doors & Windows:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Cracked glass", type: "checkbox" },
          { label: "Evidence of leaking insulated glass", type: "checkbox" },
          { label: "Broken/Missing hardware", type: "checkbox" }
        ]
      },
      {
        title: "DINING ROOM",
        items: [
          { label: "Walls & Ceiling:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" },
          { label: "Damage", type: "checkbox" },
          { label: "Moisture stains:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Floor:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Squeaks", type: "checkbox" },
          { label: "Slopes", type: "checkbox" },
          { label: "Electrical:", type: "label" },
          { label: "Switches:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Receptacles:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Safety Hazard", type: "checkbox" },
          { label: "Cover plates missing", type: "checkbox" },
          { label: "Heating Source Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Holes:", type: "label" },
          { label: "Doors", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Egress Restricted:", type: "label" },
          { label: "N/A", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Doors & Windows:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Cracked glass", type: "checkbox" },
          { label: "Evidence of leaking insulated glass", type: "checkbox" },
          { label: "Broken/Missing hardware", type: "checkbox" }
        ]
      },
      {
        title: "FAMILY ROOM",
        items: [
          { label: "Walls & Ceiling:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" },
          { label: "Damage", type: "checkbox" },
          { label: "Moisture stains:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Floor:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Squeaks", type: "checkbox" },
          { label: "Slopes", type: "checkbox" },
          { label: "Electrical:", type: "label" },
          { label: "Switches:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Receptacles:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Safety Hazard", type: "checkbox" },
          { label: "Cover plates missing", type: "checkbox" },
          { label: "Heating Source Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Holes:", type: "label" },
          { label: "Doors", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Egress Restricted:", type: "label" },
          { label: "N/A", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Doors & Windows:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Cracked glass", type: "checkbox" },
          { label: "Evidence of leaking insulated glass", type: "checkbox" },
          { label: "Broken/Missing hardware", type: "checkbox" }
        ]
      },
      {
        title: "BEDROOM",
        items: [
          { label: "Walls & Ceiling:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" },
          { label: "Damage", type: "checkbox" },
          { label: "Moisture stains:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Floor:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Squeaks", type: "checkbox" },
          { label: "Slopes", type: "checkbox" },
          { label: "Electrical:", type: "label" },
          { label: "Switches:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Receptacles:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Open ground/Reverse polarity:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Safety Hazard", type: "checkbox" },
          { label: "Cover plates missing", type: "checkbox" },
          { label: "Heating Source Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Holes:", type: "label" },
          { label: "Doors", type: "checkbox" },
          { label: "Walls", type: "checkbox" },
          { label: "Ceilings", type: "checkbox" },
          { label: "Egress Restricted:", type: "label" },
          { label: "N/A", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Doors & Windows:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Cracked glass", type: "checkbox" },
          { label: "Evidence of leaking insulated glass", type: "checkbox" },
          { label: "Broken/Missing hardware", type: "checkbox" }
        ]
      }
    ]
  },

  // INTERIOR SECTION - Page 28
  interior: {
    title: "INTERIOR",
    sections: [
      {
        title: "INTERIOR WINDOWS/GLASS",
        items: [
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Needs repair", type: "checkbox" },
          { label: "Painted shut", type: "checkbox" },
          { label: "Glazing compound needed", type: "checkbox" },
          { label: "Cracked glass", type: "checkbox" },
          { label: "Hardware missing", type: "checkbox" },
          { label: "Evidence of Leaking Insulated Glass:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "N/A", type: "checkbox" },
          { label: "Broken counter-balance mechanism", type: "checkbox" }
        ]
      },
      {
        title: "FIREPLACE",
        items: [
          { label: "None", type: "checkbox" },
          { label: "Location(s): Living Room", type: "label" },
          { label: "Type:", type: "label" },
          { label: "Gas", type: "checkbox" },
          { label: "Wood", type: "checkbox" },
          { label: "Wood burning stove", type: "checkbox" },
          { label: "Electric", type: "checkbox" },
          { label: "Vent less", type: "checkbox" },
          { label: "Material:", type: "label" },
          { label: "Masonry", type: "checkbox" },
          { label: "Metal (manufactured)", type: "checkbox" },
          { label: "Metal insert", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Damper operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Fireplace doors need repair", type: "checkbox" },
          { label: "Damper Modified for Gas Operation:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Damper missing", type: "checkbox" },
          { label: "Hearth Extension Adequate:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Mantel:", type: "label" },
          { label: "N/A", type: "checkbox" },
          { label: "Secure", type: "checkbox" },
          { label: "Loose", type: "checkbox" },
          { label: "Physical Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Recommend having flue cleaned and re-examined", type: "checkbox" }
        ]
      },
      {
        title: "STAIRS/STEPS/BALCONIES",
        items: [
          { label: "Risers/Treads:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Handrail:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Safety/needs", type: "checkbox" },
          { label: "Risers/Treads uneven", type: "checkbox" },
          { label: "Hand Rail/Railing/Balusters Recommended", type: "checkbox" },
          { label: "Headroom:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" }
        ]
      }
    ]
  },

  // BASEMENT SECTION - Page 29
  basement: {
    title: "BASEMENT",
    sections: [
      {
        title: "STAIRS",
        items: [
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Typical wear and tear", type: "checkbox" },
          { label: "Need repair", type: "checkbox" },
          { label: "Handrail:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Loose", type: "checkbox" },
          { label: "Handrail/Railing/Balusters Recommended", type: "checkbox" },
          { label: "Headway Over Stairs:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Low clearance", type: "checkbox" },
          { label: "Safety hazard", type: "checkbox" }
        ]
      },
      {
        title: "FOUNDATION",
        items: [
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Have evaluated", type: "checkbox" },
          { label: "Monitor", type: "checkbox" },
          { label: "Material:", type: "label" },
          { label: "Brick", type: "checkbox" },
          { label: "Concrete block", type: "checkbox" },
          { label: "Fieldstone", type: "checkbox" },
          { label: "Poured concrete", type: "checkbox" },
          { label: "Horizontal Cracks:", type: "label" },
          { label: "North", type: "checkbox" },
          { label: "South", type: "checkbox" },
          { label: "East", type: "checkbox" },
          { label: "West", type: "checkbox" },
          { label: "Step Cracks:", type: "label" },
          { label: "North", type: "checkbox" },
          { label: "South", type: "checkbox" },
          { label: "East", type: "checkbox" },
          { label: "West", type: "checkbox" },
          { label: "Vertical Cracks:", type: "label" },
          { label: "North", type: "checkbox" },
          { label: "South", type: "checkbox" },
          { label: "East", type: "checkbox" },
          { label: "West", type: "checkbox" },
          { label: "Covered Walls:", type: "label" },
          { label: "North", type: "checkbox" },
          { label: "South", type: "checkbox" },
          { label: "East", type: "checkbox" },
          { label: "West", type: "checkbox" },
          { label: "Basement Apparent:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Fresh", type: "checkbox" },
          { label: "Old stains", type: "checkbox" },
          { label: "Indication Of Moisture:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Condition reported above reflects visible portions only", type: "checkbox" }
        ]
      },
      {
        title: "FLOOR",
        items: [
          { label: "Material:", type: "label" },
          { label: "Concrete", type: "checkbox" },
          { label: "Dirt/Gravel", type: "checkbox" },
          { label: "Not visible/Covered with floor coverings", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" }
        ]
      },
      {
        title: "DRAINAGE",
        items: [
          { label: "Sump Pump:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Working", type: "checkbox" },
          { label: "Not working", type: "checkbox" },
          { label: "Pump not tested", type: "checkbox" },
          { label: "Floor Drains:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Drains not tested", type: "checkbox" }
        ]
      }
    ]
  },

  // CRAWL SPACE SECTION - Page 30
  crawlspace: {
    title: "CRAWL SPACE",
    sections: [
      {
        title: "CRAWL SPACE",
        items: [
          { label: "Full crawlspace", type: "checkbox" },
          { label: "Combination basement/crawl space/slab", type: "checkbox" }
        ]
      },
      {
        title: "ACCESS",
        items: [
          { label: "Exterior", type: "checkbox" },
          { label: "Interior hatch/door", type: "checkbox" },
          { label: "Via basement", type: "checkbox" },
          { label: "No Access", type: "checkbox" },
          { label: "Inspected from:", type: "label" },
          { label: "Access panel", type: "checkbox" },
          { label: "In the crawl space", type: "checkbox" }
        ]
      },
      {
        title: "FOUNDATION WALLS",
        items: [
          { label: "Material:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Have evaluated", type: "checkbox" },
          { label: "Monitor", type: "checkbox" },
          { label: "Concrete block", type: "checkbox" },
          { label: "Poured Concrete", type: "checkbox" },
          { label: "Stone", type: "checkbox" },
          { label: "Cracks", type: "checkbox" },
          { label: "Stone", type: "checkbox" },
          { label: "Piers & columns", type: "checkbox" },
          { label: "Movement", type: "checkbox" }
        ]
      },
      {
        title: "FLOOR",
        items: [
          { label: "Concrete", type: "checkbox" },
          { label: "Gravel", type: "checkbox" },
          { label: "Dirt", type: "checkbox" },
          { label: "Typical cracks", type: "checkbox" }
        ]
      },
      {
        title: "DRAINAGE",
        items: [
          { label: "Sump pump:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Pump Not tested", type: "checkbox" },
          { label: "Standing Water:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Evidence of moisture damage:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" }
        ]
      },
      {
        title: "VENTILATION",
        items: [
          { label: "Wall vents", type: "checkbox" },
          { label: "Power vents", type: "checkbox" },
          { label: "None apparent", type: "checkbox" }
        ]
      }
    ]
  },

  // PLUMBING SECTION - Page 31
  plumbing: {
    title: "PLUMBING",
    sections: [
      {
        title: "WATER SERVICE",
        items: [
          { label: "Main Shut-off Location: In the basement", type: "label" },
          { label: "Water Entry Piping:", type: "label" },
          { label: "No visible", type: "checkbox" },
          { label: "Copper/Galvanized", type: "checkbox" },
          { label: "Plastic* (PVC, CPVC, Polybutylene, PEX)", type: "checkbox" },
          { label: "Lead", type: "checkbox" },
          { label: "Lead Other Than Solder Joints:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Unknown", type: "checkbox" },
          { label: "Service entry", type: "checkbox" },
          { label: "Visible Water Distribution Piping:", type: "label" },
          { label: "Copper", type: "checkbox" },
          { label: "Galvanized", type: "checkbox" },
          { label: "Plastic* (PVC, CPVC, Polybutylene, PEX)", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Water pressure over 80 psi", type: "checkbox" },
          { label: "Functional Flow:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Valves broken/missing", type: "checkbox" },
          { label: "Pressure metal", type: "checkbox" },
          { label: "Private well:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Leaking", type: "checkbox" },
          { label: "ABS", type: "checkbox" },
          { label: "Cross connections:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Cast iron", type: "checkbox" },
          { label: "Galvanized", type: "checkbox" },
          { label: "Drain/Waste/Vent Pipe:", type: "label" },
          { label: "Copper", type: "checkbox" },
          { label: "Cast iron", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "P-traps recommended", type: "checkbox" },
          { label: "Traps Proper P-Type:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Functional Drainage:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Stainless steel", type: "checkbox" },
          { label: "CSST", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Gas Line:", type: "label" },
          { label: "Copper", type: "checkbox" },
          { label: "Galvanized", type: "checkbox" },
          { label: "Black iron", type: "checkbox" },
          { label: "Stainless steel", type: "checkbox" },
          { label: "Recommend plumber evaluate", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" }
        ]
      },
      {
        title: "MAIN FUEL SHUT-OFF LOCATION",
        subtitle: "At the gas meter",
        items: []
      },
      {
        title: "WATER HEATER(S)",
        items: [
          { label: "Brand name:", type: "label" },
          { label: "Bradford White", type: "label" },
          { label: "Serial #: TC5101546", type: "label" },
          { label: "Type:", type: "label" },
          { label: "Gas", type: "checkbox" },
          { label: "Electric", type: "checkbox" },
          { label: "Oil", type: "checkbox" },
          { label: "Capacity:", type: "label" },
          { label: "75 gal.", type: "label" },
          { label: "Approx. age: 15-20+ year(s)", type: "label" },
          { label: "Combustion Air Venting Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Relief Valve:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Extension proper:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Missing", type: "checkbox" },
          { label: "Recommend repair", type: "checkbox" },
          { label: "Vent Pipe:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Pitch proper", type: "checkbox" },
          { label: "Improper", type: "checkbox" },
          { label: "Rusted", type: "checkbox" },
          { label: "Recommend repair", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" }
        ]
      }
    ]
  },

  // HEATING SYSTEM SECTION - Page 32
  heating: {
    title: "HEATING SYSTEM",
    sections: [
      {
        title: "BOILER SYSTEM",
        items: [
          { label: "Brand Name:", type: "label" },
          { label: "Weil-McLain", type: "label" },
          { label: "Approximate age: 20-25+ year(s)", type: "label" },
          { label: "Unknown", type: "checkbox" },
          { label: "Model #: CG-8-PIDN", type: "label" },
          { label: "Energy Source:", type: "label" },
          { label: "Oil", type: "checkbox" },
          { label: "LP", type: "checkbox" },
          { label: "Electric", type: "checkbox" },
          { label: "Solid Fuel", type: "checkbox" },
          { label: "Distribution:", type: "label" },
          { label: "Hot water", type: "checkbox" },
          { label: "Baseboard", type: "checkbox" },
          { label: "Steam", type: "checkbox" },
          { label: "Radiator", type: "checkbox" },
          { label: "Circulation:", type: "label" },
          { label: "Pump", type: "checkbox" },
          { label: "Gravity", type: "checkbox" },
          { label: "Multiple zones", type: "checkbox" },
          { label: "Controls:", type: "label" },
          { label: "Temperature gauge exist:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Combustion Air Venting Present:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "DNA", type: "checkbox" },
          { label: "Relief valve:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Missing", type: "checkbox" },
          { label: "Extension proper:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "When turned on:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Recommend HVAC technician examine", type: "checkbox" },
          { label: "Before closing", type: "checkbox" }
        ]
      },
      {
        title: "OTHER SYSTEMS",
        items: [
          { label: "Gas space heater", type: "checkbox" },
          { label: "N/A", type: "checkbox" },
          { label: "Electric baseboard", type: "checkbox" },
          { label: "Radiant ceiling cable", type: "checkbox" },
          { label: "Wood burning stove", type: "checkbox" },
          { label: "Proper Operation:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "System Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" }
        ]
      }
    ]
  },

  // ELECTRICAL SECTION - Page 33
  electrical: {
    title: "ELECTRIC/COOLING SYSTEM",
    sections: [
      {
        title: "MAIN PANEL",
        items: [
          { label: "Location: Basement", type: "label" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Adequate Clearance To Panel:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Appears Grounded:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Volts 120/240", type: "checkbox" },
          { label: "Breakers", type: "checkbox" },
          { label: "Fuses", type: "checkbox" },
          { label: "GFCI Breaker:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "AFCI Breaker:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Operable:", type: "label" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "MAIN WIRE:", type: "label" },
          { label: "Copper", type: "checkbox" },
          { label: "Aluminum", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Double tapping of the main wire", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Federal Pacific Panel Sub Line", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "BRANCH WIRE:", type: "label" },
          { label: "Copper", type: "checkbox" },
          { label: "Aluminum*", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Romex", type: "checkbox" },
          { label: "BX cable", type: "checkbox" },
          { label: "Conduit", type: "checkbox" },
          { label: "Knob & tube**", type: "checkbox" },
          { label: "Double tapping", type: "checkbox" },
          { label: "Wires undersized/overloaded", type: "checkbox" },
          { label: "Panel not accessible", type: "checkbox" },
          { label: "Not evaluated", type: "checkbox" },
          { label: "Reason: This panel screw was rusted and could not get the panel off.", type: "label" }
        ]
      },
      {
        title: "SUB PANEL(S)",
        items: [
          { label: "None apparent", type: "checkbox" },
          { label: "Location 1: Basement", type: "label" },
          { label: "Location 2: Basement", type: "label" },
          { label: "Panel not accessible", type: "checkbox" },
          { label: "Not evaluated", type: "checkbox" },
          { label: "Reason:", type: "label" }
        ]
      },
      {
        title: "BRANCH WIRE:",
        items: [
          { label: "Location 1: Basement", type: "label" },
          { label: "Neutral/ground separated", type: "checkbox" },
          { label: "Yes", type: "checkbox" },
          { label: "No", type: "checkbox" },
          { label: "Copper", type: "checkbox" },
          { label: "Aluminum", type: "checkbox" },
          { label: "Not visible", type: "checkbox" },
          { label: "Branch Wire:", type: "label" },
          { label: "Copper", type: "checkbox" },
          { label: "Aluminum", type: "checkbox" },
          { label: "Neutral isolated", type: "checkbox" },
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Recommend separating/isolating neutrals", type: "checkbox" }
        ]
      },
      {
        title: "ELECTRICAL FIXTURES",
        subtitle: "A representative number of installed lighting fixtures, switches, and receptacles located inside the house, garage, and exterior walls were tested and found to be:",
        items: [
          { label: "Condition:", type: "label" },
          { label: "Satisfactory", type: "checkbox" },
          { label: "Marginal", type: "checkbox" },
          { label: "Poor", type: "checkbox" },
          { label: "Open grounds", type: "checkbox" },
          { label: "Reverse polarity", type: "checkbox" },
          { label: "GFCI's not operating", type: "checkbox" },
          { label: "Solid conductor aluminum branch wiring circuits*", type: "checkbox" },
          { label: "Recommend electrician evaluate/repair*", type: "checkbox" }
        ]
      }
    ]
  }
};

export const SYSTEM_ORDER = [
  'kitchen',
  'laundry', 
  'bathrooms',
  'rooms',
  'interior',
  'basement',
  'crawlspace',
  'plumbing',
  'heating',
  'electrical'
];